In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
type(arr)

numpy.ndarray

In [3]:
lst=[3,5,2,1,55]
type(lst)

list

In [4]:
type(np.array(lst))

numpy.ndarray

In [5]:
arr1=np.array(lst)
arr1

array([ 3,  5,  2,  1, 55])

In [6]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
type(mat)

list

In [7]:
x=np.array(mat)

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(x)

numpy.ndarray

In [10]:
arr.shape

(5,)

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
x.shape

(3, 3)

# Built-in Methods

In [16]:
print(np.arange.__doc__)


arange([start,] stop[, step,], dtype=None)

    Return evenly spaced values within a given interval.

    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.

    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.

    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
    step : number, optional
        Spacing between values.  For any output `out`, thi

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(7,20)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(7,20,3)

array([ 7, 10, 13, 16, 19])

In [33]:
np.zeros(shape=5,dtype=int, order='F')

array([0, 0, 0, 0, 0])

In [31]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [34]:
np.ones((4,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [41]:
np.arange(10,20,5)

array([10, 15])

In [42]:
np.random.rand(3)

array([0.59983382, 0.7315895 , 0.78776249])

In [43]:
np.random.random(3)

array([0.87769866, 0.85013896, 0.02511788])

In [44]:
lst=[1,2,3,4]

In [45]:
type(lst)

list

In [46]:
type(np.array(lst))

numpy.ndarray

In [47]:
mat=[[1,3,5],[2,4,6],[5,7,9]]

In [50]:
x=np.array(mat)

In [51]:
x

array([[1, 3, 5],
       [2, 4, 6],
       [5, 7, 9]])

In [52]:
np.random.rand(3)

array([0.93216776, 0.74958163, 0.18165285])

In [53]:
np.random.random(5)

array([0.09643169, 0.1828821 , 0.72393632, 0.05990458, 0.95925029])

In [54]:
arr=np.arange(1,25)

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])